### ISSUE TITLE
Исправить страницу авторизации

### ISSUE THREAD

**Issue by EAndreyF** [ya-shred/production#6]
- [x] Создать ветку 6_authorization-edit от мастера
- [x] Поменять title страницы
- [x] Центрировать блок
- [x] Адаптивность
- [x] Добавить фавиконку
- [x] Переименовать с регистрация на авторизация
- [x] Изъял файл undex.css все изменения внёс index.styl
- [x] Поправил синтаксис Стайлуса (:;)
- [x] Пул реквест. Проверить итог.

Проверить верстку, стили. Может что ещё не так

**Comment by VisualVortex** [comment]
Разберусь с этой задачей. Сразу как поиск с Ефимом присоединим к продакшину.
