### ISSUE TITLE
Перенести поиск по пользователям и поиск по сообщениям, реализовать редактирование сообщения.

### ISSUE THREAD

**Issue by efimweb** [ya-shred/production#8]
- [x] Создать таску
- [x] Создать ветку от мастера
- [x] Перенести в эту ветку компонент
- [x] Сделать пулл реквест
- [x] Андрей или Женя посмотрели пулл реквест
- [x] Мержить пулл реквест
- [x] проверить что таска закрылась, либо закрыть самому.

**Comment by VisualVortex** [comment]
предлагаю ветку назвать 8_search-compile (по шаблону вроде так)

**Comment by EAndreyF** [comment]
да, называйте

**Comment by VisualVortex** [comment]
Ефим, обрати внимание что ветка в ГитХабе уже создана 8_search-compile
я не знаю мержишь ты там или нет , я у себя пока тоже попробую. на всякий случай.
